//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnginesTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.Measurements = new HashSet<Measurement>();
        }
    
        public int Id { get; set; }
        public string UID { get; set; }
        public System.DateTime DateTime { get; set; }
        public int EngineId { get; set; }
        public int UserId { get; set; }
        public double TIncomingAir { get; set; }
        public double PBarometric { get; set; }
    
        public virtual ICollection<Measurement> Measurements { get; set; }
        public virtual Engine Engine { get; set; }
        public virtual User User { get; set; }
    }
}
