//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnginesTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Tests = new HashSet<Test>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int JobTitleId { get; set; }
        public string ProfileImage { get; set; }
        public bool SecurityUM { get; set; }
        public bool SecurityTV { get; set; }
        public bool SecurityTM { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Test> Tests { get; set; }
        public virtual JobTitle JobTitle { get; set; }
    }
}
